project/build.properties

so we can build this on Java 9 & 10 in the Scala community build

upgrade sbt 0.13.16 -> 0.13.17

---

build.sbt

@lrytz Has just published a new Scala distribution, let’s use it!

Use the latest integration of the collections

---

build.sbt

https://github.com/scala-js/scala-js/blob/v0.6.23/compiler/src/main/scala/org/scalajs/core/compiler/ScalaJSPlugin.scala#L154-L158

add -P:scalajs:mapSourceURI option

---

.travis.yml
admin/README.md
admin/build.sh

And a few small cleanups to the build scripts to bring them in line with the other repos (currently scala-xml)

Build the 2.11 version on Java 6

---

scalafix/build.sbt
scalafix/input/src/main/scala/fix/CanBuildFromNegSrc.scala
scalafix/input/src/main/scala/fix/CanBuildFromSrc.scala
scalafix/output-failure/src/main/scala/fix/CanBuildFromNegSrc.scala
scalafix/output/src/main/scala/fix/CanBuildFromSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala
scalafix/tests/src/test/scala/fix/Collectionstrawman_Tests.scala

Rewrite: CanBuildFrom to BuildFrom or Factory (fix #43)

---

scalafix/input/src/main/scala/fix/BreakoutSrc.scala
scalafix/output213/src/main/scala/fix/BreakoutSrc.scala

probably lost durring a rebase

Restore BreakoutSrc

---

scalafix/input/src/main/scala/fix/RoughlySrc.scala
scalafix/output/src/main/scala/fix/RoughlySrc.scala
scalafix/rules/src/main/scala/fix/Roughly.scala

Please check the formatting PR first: https://github.com/scala/scala-collection-compat/pull/129

Add ApplyInfix syntax for Roughly

---

README.md

Collections213 => Collection213

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/ViewTest.scala

Fixes https://github.com/scala/scala-collection-compat/issues/203

Add mapValues for IterableViews of Maps

---

.travis.yml
admin/README.md

we are standardizing on this for all modules (and, in general,
Lightbend-wide)

test on OpenJDK 8

---

build.sbt

See https://github.com/scala/scala-collection-compat/issues/276#issuecomment-564374802

Restore workaround for ci-release issue

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/ImmutableQueueTest.scala

Add enqueueAll to immutable.Queue

---

binary-compat/test/src/test/scala/BinaryCompaTest.scala
build.sbt
compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/CompatImpl.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/LazyList.scala
compat/src/test/scala/test/scala/collection/LazyListLazinessTest.scala
compat/src/test/scala/test/scala/collection/LazyListTest.scala

run scalafmt, fail build if there is a violation

---

project/build.properties

I'd like to dogfood this release to make sure that we're still able to publish our modules with it

upgrade to sbt 1.4.0-RC1

---

build.sbt
project/MultiScalaProject.scala

thank you new sbt 1.4 unused-settings warnings for catching the `LazyListGCTest` thing!!

clean up build (including a fix to make LazyListGCTest run)

---

admin/scalafmt.sh
build.sbt

get admin/scalafmt.sh working again
recently this started failing on Travis-CI

get admin/scalafmt.sh working again

---

.travis.yml
build.sbt
project/plugins.sbt

The build seems hard to adapt for 2 milestone versions. I propose closing my previous PR and just updating the current Milestone version

Switch to M3

---

compat/src/main/scala-2.11_2.12/scala/annotation/nowarn.scala

make `@nowarn` a ClassfileAnnotation, as in 2.12.13

---

project/plugins.sbt
scalafix/tests/src/test/scala/fix/ScalafixTests.scala

Update scalafix plugin

---

.github/workflows/release.yml
README.md
build.sbt

There aren't any user-visible changes to ship, so rather than testing this now, I'm just going to merge it, and at release time, if something doesn't work, we'll deal with it then. :shipit:

add publishing to GitHub Actions

---

build.sbt

set version policy for 2.8.1 release

---

build.sbt

reset version policy, post-2.11.0

---

.scala-steward.conf

as per #579 and as per remarks in comment

tell Scala Steward not to update stuff

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Add `dependabot.yml` for GitHub Actions update
