scala/scala-collection-compat

src/main/scala-2.12/collection/BuildFrom.scala
src/main/scala-2.12/collection/compat/package.scala
src/main/scala-2.12/collection/compat_impl/package.scala
src/test/scala/collection/BuildFromTest.scala
src/test/scala/collection/CollectionTest.scala
src/test/scala/collection/ImmutableArrayTest.scala

The goal of this PR is to make it possible for library authors to write code that uses the new `BuildFrom` but that still works with old Scala versions.
This PR introduces the `BuildFrom` type and derives instances from existing `CanBuildFrom` instances.

Add BuildFrom

---

.travis.yml

Downloading the jdk seems to currently fail. We might temporarily disable that and use the default jdk of Travis CI.

Don’t try to make Travis CI upgrade to a newer jdk

---

CONTRIBUTING.md
README.md
scalafix/build.sbt
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_Stream.scala
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_TupleNZipped.scala
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_copyToBuffer.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_Stream.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_TupleNZipped.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_copyToBuffer.scala
scalafix/project/build.properties
scalafix/project/plugins.sbt
scalafix/rules/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_v0.scala
scalafix/tests/src/test/scala/fix/Collectionstrawman_Tests.scala

This PR copies the content of the migration rule from the scala/collection-strawman repository.
This step is part of scala/collection-strawman#560.

Move migration rules here

---

.travis.yml
build.sbt
scalafix/build.sbt
scalafix/output/src/main/scala/fix/StreamSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_NewCollections.scala
src/main/scala-2.11_2.12/scala/collection/compat/package.scala
src/test/scala/test/scala/collection/StreamTest.scala

the goal here is to get the project green again in the 2.13 community build.
(the 2.12.6 and language warnings parts are just gravy.)
(despite the branch name, this does not enable fatal warnings, since of course on 2.13 we have deprecation warnings)

newer 2.13 snapshot, 2.12.6, fix language warnings

---

project/plugins.sbt

for the Scala 2.12 community build on Java 9, not otherwise essential

make build work on Java 9

---

src/main/scala-2.11_2.12/scala/collection/compat/package.scala
src/test/scala/test/scala/collection/CollectionTest.scala

I want to avoid deprecation warning in Scala 2.13.x but Scala 2.12 `TraversableOnce` does not have `.iterator` method.
```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.
scala> (Iterator(1) : IterableOnce[Int]).foldLeft(0)(_ + _)
^
warning: method foldLeft in class IterableOnceExtensionMethods is deprecated (since 2.13.0): Use .iterator.foldLeft instead of .foldLeft on IterableOnce
res0: Int = 1
scala> (Iterator(1) : IterableOnce[Int]).iterator.foldLeft(0)(_ + _)
res1: Int = 1
```
```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.
scala> (Iterator(1) : TraversableOnce[Int]).iterator.foldLeft(0)(_ + _)
<console>:12: error: value …
```

add "implicit class TraversableOnceExtensionMethods"

---

scalafix/input/src/main/scala/fix/CopyToBufferSrc.scala
scalafix/input/src/main/scala/fix/FoldSrc.scala
scalafix/input/src/main/scala/fix/RetainSrc.scala
scalafix/input/src/main/scala/fix/StreamSrc.scala
scalafix/input/src/main/scala/fix/TraversableSrc.scala
scalafix/input/src/main/scala/fix/TupleNZippedSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala

this is a bug introduced in:
https://github.com/scala/scala-collection-compat/commit/d63d4ea724e86c26f37e2095a9886c0a9e6c31d3#diff-04c6e90faac2675aa89e2176d2eec7d8R49
per
https://github.com/scalacenter/scalafix/blob/8490db2edf3ef9aa6291870c04e56fa37ce4537d/scalafix-reflect/src/main/scala/scalafix/internal/reflect/GitHubUrlRule.scala#L33
the url format is github:org/repo/version
we use NewCollections as the version, but it get's lowercased
```
scalafix github:scala/scala-collection-compat/NewCollections
```
gives me
```
error: 404 - not found https://raw.githubusercontent.com/scala/scala-collection-compat/master/scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala
```
workaround
```
scalafix https://raw.githubusercontent.com/scala/scala-collection-compat/master/scala …
```

fix github url

---

scalafix/input/src/main/scala/fix/SetMapSrc.scala
scalafix/output/src/main/scala/fix/SetMapSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala

The `+` operation no longer has an overload accepting multiple values
motivation:
https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes
2nd row, breaking change

Rewrite `immutable.Set/Map.+`

---

scalafix/input/src/main/scala/fix/MutSetMapSrc.scala
scalafix/output/src/main/scala/fix/MutSetMapSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala

motivation:
https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes
3nd row, breaking change

Rewrite `mutable.Set/Map` no longer have a `+` operation

---

scalafix/input/src/main/scala/fix/MutSetMapSrc.scala
scalafix/output/src/main/scala/fix/MutSetMapSrc.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala

motivation: https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes
breaking changes 4th row

Rewrite mutable.Map.updated

---

.travis.yml
admin/build.sh

We cannot use openjdk6 since maven central wont serve TLS1.0
Server access Error: Received fatal alert: protocol_version url=https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/0.13.17/compiler-interface-0.13.17.jar
see https://stackoverflow.com/a/50824799/449071

Bump openjdk6 to openjdk7

---

scalafix/input/src/main/scala/fix/ExperimentalSrc.scala
scalafix/input/src/main/scala/fix/SetMapSrc.scala
scalafix/output/src/main/scala/fix/ExperimentalSrc.scala
scalafix/output/src/main/scala/fix/SetMapSrc.scala
scalafix/rules/src/main/scala/fix/Experimental.scala
scalafix/rules/src/main/scala/fix/Scalacollectioncompat_newcollections.scala

superseded: https://github.com/scala/scala-collection-compat/pull/62 and https://github.com/scala/scala-collection-compat/pull/58

Experimental

---

.travis.yml
compat/src/main/scala-2.11_2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala
scalafix/input/src/main/scala/fix/IterableSrc.scala
scalafix/input/src/main/scala/fix/TraversableSrc.scala
scalafix/output212/src/main/scala/fix/IterableSrc.scala
scalafix/output212/src/main/scala/fix/TraversableSrc.scala
scalafix/rules/src/main/scala/fix/CanBuildFrom.scala
scalafix/rules/src/main/scala/fix/CrossCompat.scala
scalafix/rules/src/main/scala/fix/NewCollections.scala
scalafix/rules/src/main/scala/fix/Stable212Base.scala
scalafix/tests/src/test/scala/fix/ScalafixTests.scala

Add more rules to CrossCompile

---

build.sbt

This PR is to make my scalafix hack possible: https://github.com/MasseGuillaume/scalafix/commit/4108726c5239a584c440753fea9152b6d7467667
It's not possible to use bundles to fetch the migration rule for some reason. It's probably going to be useful when we have scalafix 0.6.X.

Don't use bundle to publish scalafix rules

---

scalafix/input/src/main/scala/fix/TraversableSrc.scala
scalafix/output212/src/main/scala/fix/TraversableSrc.scala
scalafix/rules/src/main/scala/fix/Stable212Base.scala
scalafix/tests/src/test/scala/fix/ScalafixTests.scala

For example: https://github.com/akka/akka/blob/9fae4e283947c956e43aa37f83156f0e728b5965/akka-actor/src/main/scala/akka/io/Udp.scala#L282-L283

Rewrite xs.to => xs.to(CC) (fix #106)

---

build.sbt

recent build changes caused "compat.jar" to be published instead of
"scala-collection-compat.jar" like before. this fixes it
caught by the Scala 2.12 community build

fix regression in artifact naming

---

build.sbt
scalafix/input/src/main/scala/fix/CompanionSrc.scala
scalafix/input/src/main/scala/fix/CompanionSrc212.scala
scalafix/input/src/main/scala/fix/ReplaceToSrc.scala
scalafix/input/src/main/scala/fix/TraversableSrc.scala
scalafix/output/src/main/scala/fix/CompanionSrc.scala
scalafix/output/src/main/scala/fix/ReplaceToSrc.scala
scalafix/output/src/main/scala/fix/TraversableSrc.scala
scalafix/output212/src/main/scala/fix/CompanionSrc212.scala
scalafix/rules/src/main/scala/fix/Stable212Base.scala
scalafix/tests/src/test/scala/fix/ScalafixTests.scala

Some Traversable were missing.

Refactor Traversable and .to[CC] rules

---

.travis.yml

I notice that the ci fetch sbt every time: 
https://travis-ci.org/scala/scala-collection-compat/jobs/411677832#L570

Add caching for sbt-launcher

---

README.md
build.sbt
project/plugins.sbt

Upgrade to scalafix v0.9.0

---

README.md

I tried the 0.2.1 migration tool and Collection213CrossCompat appears to be the right name

fix sbt task name in migration tool doc

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/NoImportTest.scala

avoid `import scala.collection.compat._` everywhere in Scala 2.12 and 2.11
```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.
scala> implicitly[scala.collection.compat.Factory[Int, List[Int]]]
<console>:12: error: could not find implicit value for parameter e: collection.compat.Factory[Int,List[Int]]
implicitly[scala.collection.compat.Factory[Int, List[Int]]]
^
scala> import scala.collection.compat._
import scala.collection.compat._
scala> implicitly[scala.collection.compat.Factory[Int, List[Int]]]
res1: collection.compat.Factory[Int,List[Int]] = scala.collection.generic.GenTraversableFactory$$anon$1@41b12185
```
```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in …
```

fix the "Factory" type alias definition

---

.travis.yml
build.sbt

not clear why it was excluded, I think it probably goes back to when we still had JDK 6 in the matrix
context: #180

re-enable Scala 2.11 in CI matrix

---

build.sbt

publish releases from JDK 8 jobs only, not JDK 11

---

compat/src/test/scala/test/scala/collection/FactoryTest.scala

I don’t know what changed since these tickets were opened but both
cases work fine now.
Closes https://github.com/scala/scala-collection-compat/issues/137 and https://github.com/scala/scala-collection-compat/issues/183

Add tests for #137 and #183

---

.travis.yml
README.md
admin/README.md
build.sbt
project/Version.scala
project/plugins.sbt

- Stubs are now built for 2.13.0-RC1 and 2.13.0-M5
- Add ScalaJS version 1.0.0-M7
- Update scala-collection-compat version to 1.0.0 and document binary
compatibility policy in the README

Update for Scala 2.13.0-RC1

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/ArraySeq.scala

- ArraySeq.ofByte.hashCode from https://github.com/scala/scala/commit/b7523eba5cc8ddf85f05b8c93a077d012fa631db#diff-a7ab156ecfe37114bc259ba947342e46
- ArraySeq.ofRef.equals from https://github.com/scala/scala/commit/3deb1a83f037a47cc4607005d01318a1475a5ba3#diff-a7ab156ecfe37114bc259ba947342e46

Backport immutable.ArraySeq bug fixes from Scala 2.13

---

project/Version.scala

by ignoring trailing `#junk` on TRAVIS_TAG
context is #210

allow republishing for new Scala versions

---

project/Version.scala

as suggested by @NthPortal at #212

minor code improvement in build

---

compat/src/main/scala-2.11_2.12/scala/jdk/CollectionConverters.scala
compat/src/test/scala/scala/jdk/CollectionConvertersTest.scala

Fixes https://github.com/scala/scala-collection-compat/issues/208

Backport scala.jdk.CollectionConverters to 2.11 / 2.12

---

build.sbt

- Export all our packages (fixes https://github.com/scala/scala-collection-compat/issues/224)
- Import the correct standard library version
(using code from https://github.com/slick/slick/blob/master/project/Osgi.scala)
- No private packages needed
This combines https://github.com/scala/scala-collection-compat/pull/225 with version-dependent exports and proper imports.

Fix OSGi headers

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/ArraySeq.scala

These three methods are the most essential methods lacking on `ArraySeq` companion object.
We could also think about adding other methods available on Scala 2.12 collection companions, i.e. everything from `SeqFactory` (which we can't simply inherit because `ArraySeq` expects a `ClassTag` for every operation).
Fixes #222

Added apply, unapplySeq and newBuilder to ArraySeq companion

---

build.sbt

Set up MiMa

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/CompatImpl.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Fixes #236 Not so much about elegance as about getting the job done.

to(Seq) doesn't evaluate collection when called on a Seq

---

build.sbt

The version parsed from the travis tag only supports M.N.P, no -suffix.
This broke sbt-ci-release / sbt-sonatype.

Use version set by sbt-dynver, not by parsing travis tag

---

README.md

Fixes #245. 
As `scala-collection-migrations` was not a part of the 2.1.2 release, this PR removes all mention of a 2.1.2 version of `scala-collection-migrations` in the README. Instead, it updates installation instructions to 2.1.1, which I suppose is the only way to mitigate the issue raised in #245.
This PR is related to #264, which fixed the instructions for the `Collection213Upgrade` rewrite, but not for the `Collection213CrossCompat` rewrite. 
I also added a line with `addCompilerPlugin(scalafixSemanticdb)`. The scalafix instructions mandate using this, but the instructions here don't contain the line. While the README does say to follow the installation instructions in scalafix, I think it makes for a better user experience to outline the steps here too.
With these updated …

Fix migration tool installation instructions

---

.travis.yml

This should enable scala-collection-migrations to be published, as
noted in https://github.com/scala/scala-collection-compat/issues/279

Move TEST_SCALAFIX / TEST_BINARY_COMPAT / TEST_SCALAFMT to jdk 8

---

README.md
build.sbt

(this won't go green until all of the 2.1.3 artifacts have hit Maven Central)

update readme and build for 2.1.3 release

---

binary-compat/test/src/test/scala/BinaryCompaTest.scala

sequel to #275. review by @dwijnand

code improvements to BinaryCompaTest

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Add groupMap and groupMapReduce extensions

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Add tapEach

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Add sizeCompare, sizeIs and lengthIs

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

fixes #247 
I don't know If I'm doing things right here... Help is appreciated. 
Please review the new `implicit def`
What needs to be written in the test?
What needs to be done regarding binary compatibility?

Add implicit: genericOrderedCompanionToCBF

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/ViewTest.scala

Fix implementation of `IterableView#filterKeys` to not require an
implicit CBF, and add a commented-out implementation of
`IterableView#mapValues` that does not require an implicit CBF.
Add an implicit method to create a CBF so that
`IterableView#mapValues` can be chained in front of
`IterableView#filterKeys`.
Fixes #294

Allow chaining of filterKeys and mapValues

---

README.md
build.sbt

Update README and MiMa to refer to version 2.1.4 instead of 2.1.3, now that 2.1.4 is published.

Refer to version 2.1.4 instead of 2.1.3

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Took the implementation from `StrictOptimizedIterableOps` in 2.13. There are also some style changes by my overly eager scalafmt. I can revert them if needed.
Closes #302.

Add partitionMap to 2.11 and 2.12

---

compat/src/main/scala-2.11/scala/collection/compat/package.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.12/scala/collection/compat/package.scala
compat/src/test/scala/test/scala/collection/LazyZipTest.scala

move conversion for lazyZip into implicit conversion method

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/LazyList.scala
compat/src/main/scala-2.13/scala/collection/compat/immutable/package.scala
compat/src/test/scala/test/scala/collection/LazyListGCTest.scala
compat/src/test/scala/test/scala/collection/LazyListLazinessTest.scala
compat/src/test/scala/test/scala/collection/LazyListTest.scala

Backport LazyList

---

project/plugins.sbt

This new version includes the travis job number in the sonatype repo
description, which ensures that travis jobs don't interfere by writing
to the same repo.
In particular, for 2.12.11, there are two travis jobs in this repo:
one for the migration rules, one for the compat library.
This is why the 2.12 release was missing last time:
https://contributors.scala-lang.org/t/this-is-not-the-release-announcement-of-scala-js-1-0-0/4021/9

Update sbt-scala-module to 2.1.4

---

build.sbt
project/plugins.sbt

As discussed at https://github.com/scala/scala-collection-compat/pull/312#issuecomment-614076407

No longer bundle as OSGi

---

compat/src/main/scala-2.11_2.12/scala/util/Using.scala
compat/src/main/scala-2.11_2.12/scala/util/control/compat/ControlThrowable.scala
compat/src/main/scala-2.13/scala/util/control/compat/package.scala
compat/src/test/scala/scala/util/UsingTest.scala
compat/src/test/scala/scala/util/control/compat/ControlThrowableTest.scala

Backport `scala.util.Using`.
Backport `scala.util.control.ControlThrowable` from
2.13 (which does not suppress exceptions or have a
stack trace) as `scala.util.control.compat.ControlThrowable`
(it still extends previous Scala versions'
`scala.util.control.ControlThrowable`).

Backport Using and new ControlThrowable

---

compat/src/main/scala-2.11_2.12/scala/annotation/nowarn.scala

The original URL is a dead link.

Update URL for Scaladoc 2.13.2

---

CONTRIBUTING.md
NOTICE
README.md
build.sbt

fixes #317
note that I already renamed the GitHub repo
#328 has the associated README.md changes separately, to be
merged once we've actually published under the new name
this PR disables MiMa, but I left a breadcrumb in #328 to remember to re-enable it later

rename to scala-library-compat

---

.scalafmt.conf
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/FactoryTest.scala

I hope that this PR is OK. I have added some tests for the correct behaviour in one commit and then a fix for the issue in a second. However, I cannot get the project to compile any tests locally (even before I have made any changes), so I have checked that the test compiles and fails elsewhere using the existing release.

Issue 337 factory.newBuilder should return new instances

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/MapTest.scala

`scala.collection.Map.foreachEntry` backport for 2.11/2.12

---

README.md

The versions in the readme don't work for scala 2.12.12, a newer version of scalafix is needed. Following them as written gives
```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.12:4.2.3
```
whereas with the changes, it works

Bump versions mentioned in readme instructions

---

CONTRIBUTING.md
NOTICE
README.md
build.sbt
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala

sigh, rename back to scala-collection-compat (and re-enable MiMa)

---

binary-compat/test/src/test/scala/BinaryCompaTest.scala
build.sbt

this will take some work, the APIs the test was using don't exist anymore
we may need to assess what this test is for and whether we really need it
fyi @dwijnand

use latest MiMa version in binary-compat test

---

compat/src/main/scala-2.11_2.12/scala/annotation/unused.scala

Solves: https://github.com/scala/scala-collection-compat/issues/369

add @unused.

---

.gitignore
.travis.yml
build.sbt

Add Scala.js source maps for Scala 3, although the option syntax slightly differs from Scala 2: https://github.com/lampepfl/dotty/issues/9783#issuecomment-731718011

Update for Scala 3.0.0-M2

---

compat/src/test/scala/test/scala/collection/BuildFromTest.scala

this future-proofs the code for scala/scala#9303, and IMO the new code is just as good anyway
the code could be even better with `withRight` (we wouldn't need to repeat `(String, Int)`), but we don't have `withRight` in 2.11/2.12
as for the reformatting, well, scalafmt insisted

avoid using type parameters on Left or Right

---

.travis.yml
build.sbt
project/MultiScalaProject.scala
project/plugins.sbt

Trying to get a little jump on this. Works locally with two Scala Native tests failing on Scala `2.11-2.13`. Was able to test `ekrich/sconfig` against the locally built version and that worked fine.
For CI
- Not sure if Scala Native SNAPSHOT will resolve 
- Not sure about the `.travis.yml` update

Update for Scala Native 0.4.0

---

.travis.yml

I got a (polite) complaint that (especially since this a very low-level, foundational library) we ought to be supporting the last two Dotty versions, not just the last one

restore Scala 3.0.0-M2 to crossbuild

---

.travis.yml
README.md
project/MultiScalaProject.scala

`compat212Native / update` is failing before this change because the `nscplugin` and `junit-plugin` are not published for Scala `2.12.12`

Update Scala 2.12 to minimum Scala Native supports

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/ArraySeq.scala

Deprecate `update` method on `i.ArraySeq` implementations,
and change the implementations of the method to throw
an `UnsupportedOperationException`.
Fixes #419

Deprecate update method on i.ArraySeq impls

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/MutableMapTest.scala

References https://github.com/scala/scala-collection-compat/issues/355

Add mutable Map.updateWith

---

build.sbt
project/plugins.sbt

Adds Scala 3 support to the Scala native build.
Scala native only works on 3.1.x+, so this adds a 3.1 project just for native (I also needed to add the `JVMPlatform`, since otherwise the crossproject wouldn't work, but it's not referenced later).
This breaks the MIMA tests (as there's no previous version). I added a quick fix to skip the tests on this version.
Supercedes #523.

Add a Scala 3 native build

---

build.sbt

The formatting check failed at https://github.com/scala/scala-collection-compat/pull/524 and I'm not sure why I didn't notice. I normally would fix something like this before merging a PR. 🤷

fix formatting to satisfy scalafmt

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/OptionTest.scala

Implementation copied from 2.13 [sources](https://github.com/scala/scala/blob/2.13.x/src/library/scala/Option.scala#L36-L47). I've also added some basic unit tests.

Option.when and Option.unless added

---

project/build.properties

it's perhaps slightly unusual to adopt an RC in a scala/* repo, but I think enough of us have had enough experience with 1.7 for it to be safe. I want to take advantage of the new support for not repeating Scala version numbers in the Actions config.
besides, dogfooding/testing 1.7 is good.

sbt 1.7.0-RC2 (was 1.6.2)

---

.github/workflows/ci.yml
build.sbt
project/Version.scala

GitHub Actions config: avoid duplicating Scala version numbers

---

.github/workflows/ci.yml
build.sbt
project/MultiScalaProject.scala
project/Version.scala

as per scala/scala-lang#1387, there's no longer any need to keep supporting Scala 3.0.x. it's fine to expect people to upgrade to 3.1 or higher
Admittedly I'm making a bit of an executive decision here. But I see this happening in many places in the ecosystem.
Also, it simplifies the build. Scala 3.0.x didn't support Scala Native, so we had to do weird stuff to publish for 3.0 on JS and JVM but 3.1 on Native. This removes those complications.

for Scala 3 users, require Scala 3.1+

---

README.md
project/plugins.sbt
scalafix/rules/src/main/scala/scala/fix/collection/Collection213Experimental.scala

https://github.com/scalameta/scalameta/pull/2684, first released in scalameta 4.5.1 (scalafix 0.10.0), changed a behavior, so this takes a more intrusive but also more robust approach so that the rule works with scalafix 0.10.x.

scalafix 0.10.1

---

README.md

The `scalafixEnable` command is used by scala-steward for more than 3 years and got [some further improvements lately](https://github.com/scalacenter/sbt-scalafix/pulls?q=is%3Apr+scalafixEnable+is%3Aclosed), so I think it's safe to rely on it instead of asking users to update their build.

scalafix: leverage scalafixEnable & scalafixAll

---

build.sbt
compat/src/main/scala-2.11/scala/jdk/javaapi/CollectionConverters.scala
compat/src/main/scala-2.12/scala/jdk/javaapi/CollectionConverters.scala
compat/src/test/scala-jvm/test/scala/jdk/javaapi/CollectionConvertersTest.java
compat/src/test/scala-jvm/test/scala/jdk/javaapi/TestObjects.scala

This PR adds 2.13 collection compatible forwarders for scala 2.11 and scala 2.12, see #346.
2.11 has converters in traits WrapAsJava and WrapAsScala, while 2.12 has them in  AsJavaConverters and AsScalaConverters.
The method names are the same, but unfortunately both CollectionConverters objects have to be separately defined for both sources, because of this import.
Tests are added in a Java file, to verify that the methods can be called as java api.

Add javaapi collection forwarders for 2.12 and 2.11

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/LazyList.scala
compat/src/test/scala-jvm/test/scala/collection/LazyListGCTest.scala

Backport fix for CVE-2022-36944 from 2.13.
Code copy-pasted in a browser.
Fixes #557

Fix CVE-2022-36944 for `LazyList`

---

README.md
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/StringParsers.scala
compat/src/test/scala-jvm/test/scala/collection/StringParsersJVMTest.scala
compat/src/test/scala/test/scala/collection/AssertThrown.scala
compat/src/test/scala/test/scala/collection/MinMaxOptionTest.scala
compat/src/test/scala/test/scala/collection/StringParsersTest.scala

Add `toIntOption` (and `Long`, `Boolean`, et al)

---

build.sbt

avoid `Compile` scope junit dependency
- https://github.com/scala-native/scala-native/issues/2540

use ScalaNativeJUnitPlugin

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/immutable/ArraySeq.scala
compat/src/test/scala/test/scala/collection/ArraySeqTest.scala

Make `ArraySeq[T]` extends `IndexedSeqOptimized[T, ArraySeq[T]]` so that operation expecting `CanBuildFrom[ArraySeq[_], T, ArraySeq[T]]` return specialized `ArraySeq[T]` instead of `IndexedSeq[T]`.
Without this, the following can't compile
```scala
val x = ArraySeq(1, 2)
val y = ArraySeq(3, 4)
val z: ArraySeq[Int] = x ++ y
```

Make ArraySeq extends IndexedSeqOptimized

---

build.sbt
compat/src/main/scala-2.11_2.12/scala/util/matching/compat/package.scala
compat/src/main/scala-2.13/scala/util/matching/compat/package.scala
compat/src/test/scala/scala/util/matching/compat/RegexOpsTest.scala

Recently stumbled on the fact that `Regex#matches` doesn't exist in 2.12
i had to change `versionPolicyIntention` to `Compatibility.BinaryCompatible` to get tests green. Mima newbie here, so don't kick me too hard here.

Add `RegexOps`

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Addressing #543 
Shamelessly lifted @xuwei-k 's recommended implementation and added a few unit tests. Happy to expand as necessary.

Add implementation of distinctBy

---

.github/workflows/ci.yml

'Node.js 12 actions are deprecated', GitHub was complaining

use newer GitHub Actions versions

---

build.sbt
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

- fix https://github.com/scala/scala-collection-compat/issues/610

add `unfold` method

---

build.sbt
compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/SortedTest.scala

- fix https://github.com/scala/scala-collection-compat/issues/583

add `maxBefore` and `minAfter`

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/main/scala-2.11_2.12/scala/collection/compat/RandomExtensions.scala
compat/src/test/scala/test/scala/util/RandomTest.scala

- https://github.com/scala/scala/commit/f9a019c400c1d1d096d2e8315fab4ac12d1ba88f

add `Random.nextLong(Long)`

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt

There is a level of consensus in the Scala Native community for dropping `0.4.x` when `0.5.0` final is released. This puts developers of libraries in a bit of an awkward situation which we understand. For perspective, we supported `0.3.x` along with `0.4.0-M2` for a long time and it was a bit of a pain for builds so this may be part of the current thinking. Also, this time around we have an active project whereas previously it was unknown when `0.4.0` final would occur.
- Adds Scala Native `0.5.0` and drops support for Scala 2.11.

Upgrade to 0.5.0 and drop Scala 2.11 for Scala Native

---

compat/src/test/scala/test/scala/collection/LazyListTest.scala

necessary because of scala/scala#10818
as caught by the Scala 2 community build

adjust a test to pass on both 2.13.14 and 15

---

build.sbt

I didn't go to 2.13.14 because I'd have to upgrade Scala.js as well and we seek to avoid doing that in this repo unless we must, for maximum compatibility
going from Scala 3.2 to 3.3 might seem inconsistent with that, but I think we should do it, because all of the messaging around Scala 3 has been super consistent that 3.3 is the first LTS version and older versions are dead. besides, 3.3 isn't at all new anymore.

Scala 3.3.3, 2.13.13, 2.12.19

---

compat/src/main/scala-2.11_2.12/scala/collection/compat/PackageShared.scala
compat/src/test/scala/test/scala/collection/CollectionTest.scala

Without the extension, code fails to compile for scala 2.11 and 2.12 with
```
value from is not a member of object Array
val a = Array.from(xs)
``` 
Add missing extension to the compat package

Add Array.from extension for scala 2.11 and 2.12

---

.github/workflows/ci.yml
build.sbt
compat/src/main/scala-2.11/scala/util/Using.scala
compat/src/main/scala-2.12/scala/util/Using.scala
compat/src/test/scala-jvm/test/scala/util/UsingTest.scala
project/plugins.sbt

ports https://github.com/scala/scala/pull/11000
fixes #692 
sequel to @NthPortal's #319
I was tempted to drop Scala 2.11, but in the end I was able to keep it in the build by special-casing it to use an older Scala.js version
I also had to do a bit of monkey business in the build for the tests to pass on Scala 3 even though Scala 3 hasn't taken the 2.13.17 upgrade yet. Once they take it, the monkey business can be removed and `UsingTest.scala` can be moved out of `src-jvm` and into `src` (since for some reason, the monkey business only worked on the JVM, not JS or Native).

update `Using` from Scala 2.13.17 and add `UsingTest`
